python calRank.py --dataset "['PEMS03']"
python calRank.py --dataset "['PEMS04']"
python calRank.py --dataset "['PEMS07']"
python calRank.py --dataset "['PEMS08']"
python calRank.py --dataset "['SD']"
python calRank.py --dataset "['GBA']"
python calRank.py --dataset "['GLA']"
python calRank.py --dataset "['CA']"
